#!/usr/bin/env bash
# Quick test script to verify admin panel is working

echo "IEEE MBITS Admin Panel - Quick Test Guide"
echo "=========================================="
echo ""
echo "1. Open your browser and navigate to:"
echo "   http://localhost:8000/admin.html"
echo ""
echo "2. Login with default credentials:"
echo "   Password: admin123"
echo ""
echo "3. Test the following features:"
echo "   ✓ Add a new event"
echo "   ✓ View events in the dashboard"
echo "   ✓ Add a gallery image"
echo "   ✓ View gallery images"
echo "   ✓ Change admin password"
echo "   ✓ Export data"
echo ""
echo "4. Verify changes appear on main pages:"
echo "   - New events appear on /events.html"
echo "   - New gallery images appear on /gallery.html"
echo ""
echo "5. Check browser console for any errors:"
echo "   Press F12, go to Console tab"
echo ""
echo "Note: If running locally, use a simple HTTP server:"
echo "   python -m http.server 8000"
echo "   or"
echo "   npx http-server"
echo ""
